name: Link check

# Allow to trigger on pull requests and manually via Github Actions
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # Use Ubuntu as environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # This external action cares about all the sphinx stuff
    - uses: ammaraskar/sphinx-action@4.3.2
      with:
        build-command: "sphinx-build -b linkcheck source/ build/"
        docs-folder: "docs/"

